SELECT A.ID,
        (CASE WHEN A.NUM <= 0.25 THEN 'CRITICAL' 
        WHEN A.NUM <= 0.5 THEN 'HIGH' 
        WHEN A.NUM <= 0.75 THEN 'MEDIUM' 
         ELSE 'LOW'
         END) COLONY_NAME
FROM (
    SELECT ID, PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) NUM
    FROM ECOLI_DATA
) A
ORDER BY ID
