SELECT E.DEPT_ID DEPT_ID, 
    (SELECT DEPT_NAME_EN FROM HR_DEPARTMENT WHERE DEPT_ID = E.DEPT_ID) DEPT_NAME_EN, 
    ROUND(AVG(E.SAL)) AVG_SAL
FROM HR_EMPLOYEES E
GROUP BY E.DEPT_ID
ORDER BY AVG_SAL DESC
