SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
INNER JOIN ITEM_TREE T
ON I.ITEM_ID = T.ITEM_ID
WHERE NOT EXISTS (SELECT 1 
                  FROM ITEM_TREE E
                 WHERE E.PARENT_ITEM_ID = I.ITEM_ID)
ORDER BY 1 DESC
