SELECT D.ID, D.GENOTYPE, (SELECT E.GENOTYPE FROM ECOLI_DATA E WHERE E.ID = D.PARENT_ID) PARENT_GENOTYPE
FROM ECOLI_DATA D
WHERE D.PARENT_ID IS NOT NULL  AND
D.GENOTYPE&(SELECT E.GENOTYPE FROM ECOLI_DATA E WHERE E.ID = D.PARENT_ID) 
AND D.GENOTYPE|(SELECT E.GENOTYPE FROM ECOLI_DATA E WHERE E.ID = D.PARENT_ID) <= D.GENOTYPE
ORDER BY 1
