SELECT T.ITEM_ID, 
        (SELECT ITEM_NAME FROM ITEM_INFO WHERE ITEM_ID = T.ITEM_ID) ITEM_NAME,
        (SELECT RARITY FROM ITEM_INFO WHERE ITEM_ID = T.ITEM_ID) RARITY
FROM ITEM_INFO I
INNER JOIN ITEM_TREE T
ON I.ITEM_ID = T.PARENT_ITEM_ID
WHERE RARITY = 'RARE'
ORDER BY 1 DESC
