SELECT YEAR(E.DIFFERENTIATION_DATE) YEAR, M.MAX_SIZE - E.SIZE_OF_COLONY YEAR_DEV, E.ID
FROM ECOLI_DATA E 
INNER JOIN 
(SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) MAX_SIZE FROM ECOLI_DATA GROUP BY YEAR(DIFFERENTIATION_DATE)) M
ON M.YEAR = YEAR(E.DIFFERENTIATION_DATE)
ORDER BY 1, 2
