SELECT SUM(H.SCORE) SCORE,
        H.EMP_NO EMP_NO,
        E.EMP_NAME EMP_NAME, 
        E.POSITION POSITION, 
        E.EMAIL EMAIL 
FROM HR_GRADE H 
INNER JOIN HR_EMPLOYEES E
ON H.EMP_NO = E.EMP_NO 
GROUP BY H.EMP_NO
ORDER BY SCORE DESC
LIMIT 1
