SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
WHERE ((SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')&D.SKILL_CODE != 0) or
        ((SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')&D.SKILL_CODE != 0)
ORDER BY ID
