SELECT CASE WHEN 
        (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')&D.SKILL_CODE AND 
        (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End' GROUP BY CATEGORY)&D.SKILL_CODE 
        THEN 'A'
        WHEN (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')&D.SKILL_CODE THEN 'B'
        WHEN (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End' GROUP BY CATEGORY)&D.SKILL_CODE
        THEN 'C'    
    END GRADE, D.ID, D.EMAIL
FROM DEVELOPERS D
HAVING GRADE IS NOT NULL
ORDER BY 1, 2
